# Generated by Django 2.1.5 on 2019-04-15 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainShopApp', '0002_auto_20190415_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemimg',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainShopApp.Item'),
        ),
    ]
