# Generated by Django 2.1.5 on 2019-04-15 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainShopApp', '0004_auto_20190415_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemimg',
            name='img',
            field=models.ImageField(upload_to='MainShopApp/media'),
        ),
    ]
