# Generated by Django 2.1.5 on 2019-04-15 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainShopApp', '0007_remove_item_aviable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemimg',
            name='item',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='MainShopApp.Item'),
        ),
    ]
