# Generated by Django 2.1.5 on 2019-04-15 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainShopApp', '0010_auto_20190415_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemimg',
            name='img',
            field=models.ImageField(upload_to='images'),
        ),
    ]
