# Generated by Django 2.1.5 on 2019-04-15 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainShopApp', '0012_auto_20190415_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemimg',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imgs', to='MainShopApp.Item'),
        ),
    ]
