# Generated by Django 2.1.5 on 2019-04-15 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainShopApp', '0013_auto_20190415_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('for_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainShopApp.Item', verbose_name='Выберите товар')),
            ],
        ),
    ]
