# Generated by Django 2.1.5 on 2019-04-18 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainShopApp', '0014_dayitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=100)),
                ('adress', models.CharField(max_length=100)),
                ('delivery', models.CharField(max_length=50)),
                ('items', models.TextField(max_length=1000)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
