# Generated by Django 2.1.5 on 2019-04-18 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainShopApp', '0018_managers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Managers',
        ),
    ]
